[package]
name = "payments_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
rust_decimal = "1.35"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.24"
